# Generated by Django 2.1.4 on 2020-07-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profil_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
