# Generated by Django 3.0.8 on 2020-07-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200707_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profil_pic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
