# Generated by Django 3.0.8 on 2020-07-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200707_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profil_pic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
