# Generated by Django 3.0.8 on 2020-07-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200707_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profil_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/'),
        ),
    ]
