# Generated by Django 3.0.8 on 2020-09-15 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200708_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_currency', models.CharField(max_length=3)),
                ('variable_currency', models.CharField(max_length=3)),
                ('rate', models.FloatField()),
            ],
            options={
                'verbose_name': 'RateList',
                'verbose_name_plural': 'RateLists',
            },
        ),
    ]
