# Generated by Django 3.0.7 on 2020-09-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_ratelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
