# Generated by Django 3.0.8 on 2020-09-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='terms_confirmed',
            field=models.BooleanField(null=True),
        ),
    ]
